services:
  - type: web
    name: greenore-backend
    rootDir: greenore-backend
    runtime: docker
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: CORS_ORIGIN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        value: "postgresql://postgres.gbpgldqqwupcdqlhzffg:kPPVq$/Vww9.Jgm@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres"
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: 6379
      - key: PYTHON_PATH
        value: /usr/bin/python3
    healthCheckPath: /docs
    autoDeploy: true

